services:
  # Node.js Application Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://db:27017/myapp
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - isolated


  # Database Service (Example using MongoDB)
  # (uncomment ports to allow LAN access)
  db:
    image: mongo:7.0
    #    ports: #
    #      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh db:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - isolated

volumes:
  mongo_data:

networks:
  isolated:
    driver: bridge